AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - med.voll.api::MedVollAluraSpringBoot
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MedVollAluraSpringBoot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: med.voll.api.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MedVollAluraSpringBoot:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: MedVollAluraSpringBoot
